site_name: Model fit tools documentation

plugins:
  - mkdocstrings
  
theme:
  name: "material"
  palette: 
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_url: https://github.com/the-wise-lab/model-fit-tools
repo_name: the-wise-lab/model-fit-tools